---
- hosts: localhost
  connection: localhost
  gather_facts: false

  vars_files:
    - vars/api_key.yml

  tasks:
    - name: Echo the API key which was injected into the env.
      shell: echo $API_KEY
      environment:
        API_KEY: "{{ my_api_key }}"
      register: echo_result

    - name: Show the echo_resut.
      debug: var=echo_result.stdout